### ISSUE TITLE
KeyError at /spi: 'pages'

### ISSUE THREAD

**Issue by roysmith** [roysmith/spi-tools#174]
Environment:

Request Method: GET
Request URL: https://spi-tools-dev.toolforge.org/spi/

Django Version: 3.1.7
Python Version: 3.7.3
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'cat_checker',
 'spi',
 'pageutils',
 'wiki_interface',
 'tools_app.apps.ToolsAppConfig',
 'tools_app.templatetags.tools_tags',
 'social_django',
 'debug_toolbar']
Installed Middleware:
['log_request_id.middleware.RequestIDMiddleware',
 'debug_toolbar.middleware.DebugToolbarMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'social_django.middleware.SocialAuthExceptionMiddleware',
 'tools_app.middleware.RequestAugmentationMiddleware',
 'tools_app.middleware.LoggingMiddleware']

Traceback (most recent call last):
  File "/data/project/spi-tools-dev/www/python/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/data/project/spi-tools-dev/www/python/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/project/spi-tools-dev/www/python/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/data/project/spi-tools-dev/www/python/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "./spi/views.py", line 55, in get
    'choices': self.generate_select2_data(case_name=case_name),
  File "./spi/views.py", line 88, in generate_select2_data
    names = cache.get_or_set('IndexView.case_names', IndexView.get_case_names, 300)
  File "/data/project/spi-tools-dev/www/python/venv/lib/python3.7/site-packages/django/core/cache/backends/base.py", line 171, in get_or_set
    default = default()
  File "./spi/views.py", line 114, in get_case_names
    return get_current_case_names(wiki)
  File "./spi/spi_utils.py", line 273, in get_current_case_names
    overview = wiki.page(template_name).text()
  File "./wiki_interface/wiki.py", line 255, in page
    return Page(self, title)
  File "./wiki_interface/wiki.py", line 284, in __init__
    self.mw_page = self.wiki.site.pages[title]
  File "/data/project/spi-tools-dev/www/python/venv/lib/python3.7/site-packages/mwclient/listing.py", line 234, in __getitem__
    return self.get(name, None)
  File "/data/project/spi-tools-dev/www/python/venv/lib/python3.7/site-packages/mwclient/listing.py", line 265, in get
    return cls(self.site, full_page_name, info)
  File "/data/project/spi-tools-dev/www/python/venv/lib/python3.7/site-packages/mwclient/page.py", line 35, in __init__
    info = six.next(six.itervalues(info['query']['pages']))

Exception Type: KeyError at /spi/
Exception Value: 'pages'

**Comment by roysmith** [comment]
I suspect this is a mis-formatted index page.
