### ISSUE TITLE
ValueError at /spi/sock-select/TheLawGiverOfDFT/

### ISSUE THREAD

**Issue by roysmith** [roysmith/spi-tools#185]
Environment:

Request Method: GET
Request URL: https://spi-tools-dev.toolforge.org/spi/sock-select/TheLawGiverOfDFT/

Django Version: 3.1.12
Python Version: 3.7.3
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'cat_checker',
 'spi',
 'pageutils',
 'wiki_interface',
 'tools_app.apps.ToolsAppConfig',
 'tools_app.templatetags.tools_tags',
 'social_django',
 'debug_toolbar']
Installed Middleware:
['log_request_id.middleware.RequestIDMiddleware',
 'debug_toolbar.middleware.DebugToolbarMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'social_django.middleware.SocialAuthExceptionMiddleware',
 'tools_app.middleware.RequestAugmentationMiddleware',
 'tools_app.middleware.LoggingMiddleware']

Traceback (most recent call last):
  File "/data/project/spi-tools-dev/www/python/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/data/project/spi-tools-dev/www/python/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/project/spi-tools-dev/www/python/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/data/project/spi-tools-dev/www/python/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "./spi/views.py", line 163, in get
    user_infos = list(get_sock_names(wiki, case_name))
  File "./spi/views.py", line 147, in get_sock_names
    case = CacheableSpiCase.get(wiki, master_name)
  File "./spi/spi_utils.py", line 63, in get
    list(spi_case.find_all_users()),
  File "./spi/spi_utils.py", line 151, in find_all_users
    for user in day.find_users():
  File "./spi/spi_utils.py", line 186, in find_users
    username = template.get('1').value
  File "/data/project/spi-tools-dev/www/python/venv/lib/python3.7/site-packages/mwparserfromhell/nodes/template.py", line 230, in get
    raise ValueError(name)

Exception Type: ValueError at /spi/sock-select/TheLawGiverOfDFT/
Exception Value: 1

**Comment by ChristopherSWest** [comment]
@roysmith, I'm not seeing an error from that request URL anymore.  I was a moment ago.  Is this still an issue?

**Comment by roysmith** [comment]
This was broken markup in the SPI page, fixed in [this edit](https://en.wikipedia.org/w/index.php?title=Wikipedia:Sockpuppet_investigations/TheLawGiverOfDFT&diff=1032514725&oldid=1032514110&diffmode=source)
