### ISSUE TITLE
Server error on G5 request

### ISSUE THREAD

**Issue by Dreamy-Jazz** [roysmith/spi-tools#221]
Traceback:

```
Environment:

Request Method: GET
Request URL: https://spi-tools-dev.toolforge.org/spi/g5/Cuty%20Pie%20Sweetu

Django Version: 3.1.14
Python Version: 3.7.3
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'cat_checker',
 'search',
 'spi',
 'api',
 'pageutils',
 'wiki_interface',
 'tools_app.apps.ToolsAppConfig',
 'social_django',
 'debug_toolbar']
Installed Middleware:
['log_request_id.middleware.RequestIDMiddleware',
 'debug_toolbar.middleware.DebugToolbarMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'social_django.middleware.SocialAuthExceptionMiddleware',
 'tools_app.middleware.RequestAugmentationMiddleware',
 'tools_app.middleware.LoggingMiddleware']



Traceback (most recent call last):
  File "/data/project/spi-tools-dev/www/python/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/data/project/spi-tools-dev/www/python/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/project/spi-tools-dev/www/python/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/data/project/spi-tools-dev/www/python/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "./spi/g5_view.py", line 50, in get
    self.g5_score(page)))
  File "./spi/g5_view.py", line 60, in g5_score
    revisions = list(itertools.islice(page.revisions(), 50))
  File "./wiki_interface/wiki.py", line 440, in revisions
    rev['user'],

Exception Type: KeyError at /spi/g5/Cuty Pie Sweetu
Exception Value: 'user'
```

**Comment by roysmith** [comment]
This failed in wiki.Page.revisions() on a revision where the user attribute had been RevDelled:

```
rev | OrderedDict([
              ('revid', 1028654787),
              ('parentid', 1028584651),
              ('userhidden', ''),
              ('timestamp', 
              time.struct_time(tm_year=2021, tm_mon=6, tm_mday=15, tm_hour=7, tm_min=44, tm_sec=8, tm_wday=1, tm_yday=166, tm_isdst=-1)),
              ('comment', '')])
```

**Comment by roysmith** [comment]
Note: if you try to run this same query, it'll still fails, but now the problem is there's so many edits to examine in this case, it times out after about 5 minutes.  But that's a different problem.

Thanks for the report.

**Comment by Dreamy-Jazz** [comment]
No problem. Good to hear it's fixed.
