### ISSUE TITLE
selectize is not a function

### ISSUE THREAD

**Issue by roysmith** [roysmith/spi-tools#31]
In IndexView:

jquery.slim.min.js:2 jQuery.Deferred exception: $(...).selectize is not a function TypeError: $(...).selectize is not a function
    at HTMLDocument.<anonymous> (https://spi-tools-dev.toolforge.org/spi/:231:24)
    at l (https://tools-static.wmflabs.org/cdnjs/ajax/libs/jquery/3.3.1/jquery.slim.min.js:2:29567)
    at c (https://tools-static.wmflabs.org/cdnjs/ajax/libs/jquery/3.3.1/jquery.slim.min.js:2:29869) undefined

**Comment by roysmith** [comment]
Fixed in 57bcb59eb43b709e26b397776b8f531deea3ea7e.
